# Generated by Django 3.2.7 on 2022-08-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_stock_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
