# Generated by Django 3.2.7 on 2022-08-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_record_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='isWork',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminder',
            name='record_day',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
