# Generated by Django 3.2.7 on 2022-08-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220806_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='record_day',
        ),
        migrations.AddField(
            model_name='reminder',
            name='work_day',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
