# Generated by Django 3.2.7 on 2022-08-06 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220806_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='isWork',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='work_day',
        ),
    ]
